### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [mbj/stratosphere#185]
```
stratosphere                   > /tmp/stack-04132f001b52a30d/stratosphere-0.59.1/library/Stratosphere/Helpers.hs:21:27: error:
stratosphere                   >     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
stratosphere                   >     • In the first argument of ‘(.=)’, namely ‘field’
stratosphere                   >       In the first argument of ‘(.)’, namely ‘(field .=)’
stratosphere                   >       In the first argument of ‘fmap’, namely ‘((field .=) . toJSON)’
stratosphere                   >    |
stratosphere                   > 21 | maybeField field = fmap ((field .=) . toJSON)
stratosphere                   >    |                           ^^^^^
stratosphere                   > 
stratosphere                   > /tmp/stack-04132f001b52a30d/stratosphere-0.59.1/library/Stratosphere/Helpers.hs:57:26: error:
stratosphere                   >     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
stratosphere                   >     • In the first argument of ‘(.=)’, namely ‘itemName x’
stratosphere                   >       In the expression: itemName x .= nameToJSON x
stratosphere                   >       In the first argument of ‘fmap’, namely
stratosphere                   >         ‘(\ x -> itemName x .= nameToJSON x)’
stratosphere                   >    |
stratosphere                   > 57 |     object $ fmap (\x -> itemName x .= nameToJSON x) xs
stratosphere                   >    |                          ^^^^^^^^^^
```
